# Generated by Django 4.0.2 on 2022-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
    ]
