# Generated by Django 4.1.3 on 2022-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
