# Generated by Django 4.1.3 on 2022-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantity_in_stock'),
        ('orders', '0009_productinbasket_quantity_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='quantity_in_stock',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='quantity_in_stock',
            field=models.ManyToManyField(related_name='quantity', to='products.product'),
        ),
    ]
