# Generated by Django 4.1.3 on 2022-12-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_productinbasket_quantity_in_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='quantity_in_stock',
        ),
    ]
