# Generated by Django 4.0.2 on 2022-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nmb', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Тестовый продукт',
                'verbose_name_plural': 'Тестовые продукты',
            },
        ),
    ]
