# Generated by Django 4.0.2 on 2022-03-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTest',
        ),
    ]
